### ISSUE TITLE
请求更换大气层

### ISSUE THREAD

**Issue by lsp199308** [JiuXia2025/SwitchScript#1]
由于下一个版本大气层屏蔽了es补丁，主要是fusee引导的时候，请求更换这里的https://github.com/borntohonk/Atmosphere，他将es，fs，nifm添加进大气层源码了，并且屏蔽了大气层对于盗版的限制

此外这里的大气层支持演示机，但是有对盗版的限制，如果可能也请添加，谢谢https://github.com/ZachyCatGames/Atmosphere

**Comment by JiuXia2025** [comment]
了解了，将在脚本的下一个commit加入

**Comment by JiuXia2025** [comment]
这仓库的release里没自带的fusee.bin

**Comment by lsp199308** [comment]
> 这仓库的release里没自带的fusee.bin

已经有了，位于bootloader/payload下

**Comment by JiuXia2025** [comment]
感谢推荐！搞定了，最新版本的构建就是去除屏蔽的那个大气层放在release里了
用的是：https://github.com/borntohonk/Atmosphere
